class ResourceNotFound(Exception):
    pass


class AlreadyExist(Exception):
    pass
